name: Autonolas registry
on:
  push:
    branches:
      - main
    paths:
      - 'apps/autonolas-registry/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/autonolas-registry/**'

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn nx lint autonolas-registry
      - name: Run Test
        run: yarn nx test autonolas-registry
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.7'
      - run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.10.1/gitleaks_8.10.1_linux_x64.tar.gz && \
          tar -xzf gitleaks_8.10.1_linux_x64.tar.gz && \
          sudo install gitleaks /usr/bin && \
          gitleaks detect -r apps/autonolas-registry/gitleaks-report.json -s apps/autonolas-registry  -v
