name: Autonolas registry
on:
  push:
    branches:
      - main
    paths:
      - 'apps/autonolas-registry/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/autonolas-registry/**'

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn nx lint autonolas-registry
      - name: Run Test
        run: yarn nx test autonolas-registry
