name: contribute
on:
  push:
    branches:
      - main
    paths:
      - 'apps/contribute/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/contribute/**'

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn nx lint contribute
      - name: Run Test
        run: yarn nx test contribute