# TODO: figure out how to trigger workflow from vercel for nx

name: Launch
on:
  push:
    branches:
      - main
    paths:
      - 'apps/launch/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/launch/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '22.x'
      - name: Cache node modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run ESLint
        run: yarn nx lint launch
      - name: Run Test
        run: yarn nx test launch
